### ISSUE TITLE
@bassist/eslint 升级到 @0.4.0 后部分检测规则失效

### ISSUE THREAD

**Issue by rayadaschn** [chengpeiquan/bassist#18]
场景: @bassist/eslint 单独由 @0.3.1 升级到 @0.4.0 后部分检测规则失效;

复现: 如图下所示，@0.4 版本的 eslint[vue/attributes-order](https://eslint.vuejs.org/rules/attributes-order.html) 规则失效；

<img width="669" alt="image" src="https://github.com/chengpeiquan/bassist/assets/115447518/aee3767d-4034-4abd-b48c-20e1bbd1521a">

**Comment by chengpeiquan** [comment]
_(:з)∠)_ 还真是，Vue 这里只是增加了 `GLOB_EXCLUDE` 的 igrone ，针对的是一些 dist 目录之类的，理论上不影响才对，我晚上回家再排查一下，午休时间过的真快 - -

不过 0.4.0 主要是增加 Svelte 的 ESLint ，如果不是 Svelte 项目可不升级（这个是 [CHANGELOG](https://github.com/chengpeiquan/bassist/blob/main/packages/eslint/CHANGELOG.md) ）

**Comment by rayadaschn** [comment]
> _(:з)∠)_ 还真是，Vue 这里只是增加了 `GLOB_EXCLUDE` 的 igrone ，针对的是一些 dist 目录之类的，理论上不影响才对，我晚上回家再排查一下，午休时间过的真快 - -
> 
> 不过 0.4.0 主要是增加 Svelte 的 ESLint ，如果不是 Svelte 项目可不升级（这个是 [CHANGELOG](https://github.com/chengpeiquan/bassist/blob/main/packages/eslint/CHANGELOG.md) ）

哈哈哈，是的！我也看了 Git History，发现也是只添加了 Svelte，但是没有找到问题原因 😭，放弃了

**Comment by chengpeiquan** [comment]
今天排查了一下，确实是因为 Svelte 的原因导致 Vue 的规则失效，经过一些测试，主要原因在于 `svelte-eslint-parser` 和 `eslint-plugin-svelte` 这两个 Svelte ESLint 的相关依赖。

刚才发布了 `0.5.0` 版本，通过拆包的方案解决了这个情况，对于 Vue 项目，保持原来的用法不变，对于 Svelte 项目，`svelte` 需要从子包导入，具体可以看最新的 [README](https://github.com/chengpeiquan/bassist/tree/main/packages/eslint#presets)
